package hello;
/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'teekay' at '8/8/16 9:18 PM' with Gradle 2.14
 *
 * @author teekay, @date 8/8/16 9:18 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
